apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::861359358691:role/eksctl-simple-jwt-api1-nodegroup-NodeInstanceRole-1C3LO0Q05WFIQ
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::861359358691:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-20T14:39:41Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-02-20T14:39:41Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1411"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: a1cb3f58-eee5-4d8c-a75f-a95bd6643b1a
