apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::861359358691:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1L2AHHEUSHT9W
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::861359358691:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-25T18:06:29Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-02-25T18:06:29Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1634"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: e84d056d-919c-41dc-8673-e0ded0294cdb
