apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::861359358691:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1XM9O3UX1LOYA
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::861359358691:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-21T18:28:16Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-02-21T18:28:16Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1410"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 76c8a94f-898e-47d2-bd7a-a879a0145fb3
